### ISSUE TITLE
soybean animated, when click, does not transition to regular place anymore

### ISSUE THREAD

**Issue by SarahDowling** [SarahDowling/infographic-effects-interactivity#6]
@thomasjbradley

Looks like a similar issue to the jumping kids not transitioning properly. When the class making them animate before the click is removed by the click, the bean does not animate back to starting position, just jumps there.

`bean {
  transition: all 1s linear;
}
# soybeans {

  transform: translate(0, 0);
  transition: all 1s linear;
}

.bean-wiggle {
  animation: bean-wiggle-keyframes 1s infinite linear;
}

@keyframes bean-wiggle-keyframes {

  0% {
    transform: translate(160px, -50px);
  }

  50% {
    transform: translate(160px, -80px);
  }

  100% {
    transform: translate(160px, -50px);
  }
}`

`$('#soybeans').on('click', function () {
  $(this).removeClass('bean-wiggle');
  $('.soy-label').removeClass('bean-label-hide');
});
`

**Comment by thomasjbradley** [comment]
Did we fix this one in class? I honestly can't remember...

**Comment by SarahDowling** [comment]
Yeah we got it, I forgot to close this one. Thanks again for all of your help today, I'm really happy with how  it all turned out!
